### PR TITLE
TEIID-5413: Adding an option not to include the DDL with VDB payload …

### PR DESCRIPTION
**Pull request by rareddy**
…of the list-vdb and get-vdb CLI calls (#1091)

### CODE REVIEW

**Comment by johnathonlee** [comment]
@rareddy I'm getting errors in tests after pulling this locally.  Can you double check against the latest https://github.com/teiid/teiid/tree/64-8.12.x

**Comment by rareddy** [comment]
I see this test fail 
TestCommSockets.testAnonSSLConnect:213->helpEstablishConnection:192 » SingleInstanceCommunication

without my patch, can we fix this first?

**Comment by johnathonlee** [comment]
explicitly declare JDK 1.7:  export JAVA_HOME=/usr/java/jdk1.7.0_80/

**Comment by rareddy** [comment]
Looks like I do not have JDK 1.7 anymore, what are test failures are you seeing?

**Comment by johnathonlee** [comment]
```
Tests in error: 
  TestTeiidConfiguration.testOutputPerisitence:104->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testOutputModel:121->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testDescribeHandler:78->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testMinimumConfiguration:95->AbstractSubsystemBaseTest.standardSubsystemTest:96->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testAddRemoveTransport:224->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testQueryOperations:196->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testSchema:135->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration.testTranslator:301->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
  TestTeiidConfiguration>AbstractSubsystemBaseTest.testSubsystem:81->AbstractSubsystemBaseTest.standardSubsystemTest:96->AbstractSubsystemBaseTest.standardSubsystemTest:100->AbstractSubsystemBaseTest.standardSubsystemTest:134 » Runtime
```

**Comment by rareddy** [comment]
@johnathonlee updated the commit try now

**Comment by johnathonlee** [comment]
@rareddy That did it,  thanks!

**Pull request closed without merging**
