### PR TITLE
Adds extra method for getting secretKey in simpledb

### PR DESCRIPTION
**Pull request by ciphereck**
Signed-off-by: Mudit Jain <ciphereck@gmail.com>

### CODE REVIEW

**Comment by ciphereck** [comment]
https://github.com/teiid/teiid-spring-boot/pull/281#discussion_r456428526

**Comment by shawkins** [comment]
I made a further simplification to have just the secret key method on interface.

**Comment by rareddy** [comment]
cool, then we do not need the verbose method on the spring boot side @ciphereck can make the correction?

**Comment by ciphereck** [comment]
> I made a further simplification to have just the secret key method on interface.

What kind of simplification are you talking about? Is it like your simplification will let us change change things in resource adapter too? @shawkins 


> cool, then we do not need the verbose method on the spring boot side @ciphereck can make the correction?

I'm not sure, what's the correct we need?  @rareddy

**Comment by ciphereck** [comment]
Sorry. I just saw shawkins commit. Got what's the chnage and whats the correction on spring boot side. I'll add the changes asap.

**Comment by ciphereck** [comment]
This is the further simplification for future reference:
https://github.com/teiid/teiid/commit/ffcc3fcd511a8545df860c6836e008c6e4c70999

**Pull request merged**
