### PR TITLE
Adding back the spring framework jars needed for soap

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by shawkins** [comment]
Hasn't the kitting been this way since https://issues.jboss.org/browse/TEIID-3185 - https://github.com/teiid/teiid/blob/e526c6641422f85b7dd6112909b3b2c78767ecaa/connectors/connector-ws/kits/jboss-as7-dist.xml

Has there been paths that haven't been working since 8.9?  Do we need an integration test here?

**Comment by vhalbert** [comment]
This issue was only found from the use of SOAP generation from Designer.   My guess is not many people have tried this feature in the community.

**Comment by rareddy** [comment]
Are you sure you do not need the versions at the end of those jars?

**Comment by vhalbert** [comment]
i think ur right

**Comment by vhalbert** [comment]
I verified the jar's where getting put there, and

**Pull request closed without merging**
