### PR TITLE
Upgraded com.fasterxml.jackson versions to 2.11.0.rc1 and joda-time to 2.9.9

### PR DESCRIPTION
**Pull request by vhalbert**
These changes need to be backported to the 13.1.x branch.

### CODE REVIEW

**Comment by shawkins** [comment]
We have the similar problems with the dependabot bump #1246 - there's other libraries that are stuck at particular versions of databind.  And for some reason they have even removed classes in fix releases.

In the logs for this change we see:

```
[0m[31m12:53:32,109 ERROR [stderr] (Worker1)  Exception in thread "Worker1" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
[0m[31m12:53:32,109 ERROR [stderr] (Worker1)  	at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.getXmlMapper(ClientODataDeserializerImpl.java:109)
[0m[31m12:53:32,110 ERROR [stderr] (Worker1)  	at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.toMetadata(ClientODataDeserializerImpl.java:139)
[0m[31m12:53:32,110 ERROR [stderr] (Worker1)  	at org.teiid.translator.odata4.ODataExecutionFactory.getSchema(ODataExecutionFactory.java:163)
[0m[31m12:53:32,110 ERROR [stderr] (Worker1)  	at org.teiid.translator.odata4.ODataMetadataProcessor.getSchema(ODataMetadataProcessor.java:99)
```

**Comment by vhalbert** [comment]
Think I found the fix by upgrading:
+                <groupId>com.github.fge</groupId>
+                <artifactId>jackson-coreutils</artifactId>
+                <version>1.8</version>
I duplicated the error above and then it appears fixed with this change.   I'll submit the change now.

**Comment by shawkins** [comment]
Still no good.  Fails with the same error.  Do we need the dep.log checked in?

**Comment by shawkins** [comment]
See #1268

**Pull request closed without merging**
