### PR TITLE
[TEIID-5785] Changing profiles so that core-release only builds specific connectors

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by shawkins** [comment]
This doesn't look right for community master. The default profile and any profile that the community (dev, final-release) uses should have all of the translators.

**Comment by vhalbert** [comment]
> This doesn't look right for community master. The default profile and any profile that the community (dev, final-release) uses should have all of the translators.

Instead of duplicating all in each profile, the global modules is picked up by all profiles.  Otherwise, if u choose, I can change to remove the global modules section and then each profile will control only what it wants

**Comment by vhalbert** [comment]
Changed so that all the profiles (except core-release) have all the modules.

**Comment by shawkins** [comment]
What about https://github.com/teiid/teiid/pull/1165

**Pull request closed without merging**
