### PR TITLE
TEIID-4709 enables JDG authenticatioin and also fixes TEIID-4736

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by vhalbert** [comment]
This was tested by restarting JDG several times while the user was logged in.  The connection was cleaned up and recreated without impact to the user (user didn't have to relogin).

**Comment by vhalbert** [comment]
noted also, use the PoolBySubject:


                            <security>
                                <security-domain>teiid-security</security-domain>
                            </security>

**Comment by shawkins** [comment]
If there is no subject with the connection request the attempt will just fail correct?

**Comment by vhalbert** [comment]
Default, no.   Default (current) logic doesn't use the username/password.   If the authentication is configured (i.e., AuthSASLMechanism is set) then it will require either a subject or username/password.  And if that is null, you get the JDG authentication exception.

**Comment by vhalbert** [comment]
the defualt usecase is more for out-of-the-box ability to just play with it.

**Comment by vhalbert** [comment]
the PR for the SSL feature will have to be reworked with these change.

**Pull request merged**
