### PR TITLE
Updates for product build

### PR DESCRIPTION
**Pull request by vhalbert**
Removed SNAPSHOT from version, fixed poms for product build, and had to turn off TestODataIntegration test for now as it will not work due to changes, and fixed the jboss-as kit to align for product

### CODE REVIEW

**Comment by shawkins** [comment]
What is your issue with TestODataIntegration?  With these changes the integration tests won't run for me at all since there is no standalone configuration.

**Comment by vhalbert** [comment]
There must have been changes to the class it extends (BaseResourceTest), because the @BeforeClass wouldn't compile.

**Comment by vhalbert** [comment]
ah, for the standalone, we can add that back.    I removed it thinking it was only used for the jboss-as kit, and for which it is eventually removed and not available for use in DV.

**Comment by shawkins** [comment]
Can it be added back to the kit, or should there be something special just for the integration tests?

**Comment by vhalbert** [comment]
it can be added back, not an issue.

**Comment by shawkins** [comment]
The next things that I'm seeing is that the olingo-patches was removed (but is still needed) and it looks like the version.com.fasterxml.jackson.swagger is needed.

**Comment by vhalbert** [comment]
removed?? i see the sub-project, but I had to add the module to the module list in the root pom.xml in order to get it built before the connectors.

**Comment by shawkins** [comment]
removed from the kitting along with teiid-olingo-common.  But those were from the latest changes to the branch so it could have been inadvertant.

**Comment by vhalbert** [comment]
I bet I missed those when I applied the changes from my branch.

**Comment by shawkins** [comment]
Have a look at the next commit to see if there is anything you want to refine from there.

**Pull request merged**
