### PR TITLE
TEIID-5833 mostly removing the concept of namespaces

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by shawkins** [comment]
These changes don't completely remove parsing support for set namespace, rather it will fail for anything that doesn't exactly match something that is built-in.  This minimizes the breakage as we did emit the built-in declarations in our ddl.  What won't work:

* a custom prefix for a built-in namespace
* a custom namespace

The sys.properties table for now will display properties with built-in keys in both their old and new formats - note that the sysadmin.sql file did not change and it still contains references to the old uri fqn keys.  So this as well minimizes the scope of the breakage.

Codewise there is a lot of changes (constants renamed, methods removed) in public apis that should only affect those using custom namespaces.

Any new ddl to string will not emit any set namespace statements.

**Comment by rareddy** [comment]
What is the procedure for defining the extension properties for the custom translator now?

**Comment by shawkins** [comment]
You use whatever key you want.  We'll recommend using a prefix.  For existing users that want backwards compatibility you'd just use the uri fqn in whole.

**Comment by rareddy** [comment]
ok, as long as the component and DDL match the property is valid :+1:

**Pull request merged**
