### PR TITLE
[TEIID-5793] Upgrade commons-configuration to 1.7

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by vhalbert** [comment]
duplicated locally with jdk11

**Comment by shawkins** [comment]
When you say duplicated locally, you mean that the build fails for you with Java 11?

**Comment by vhalbert** [comment]
Yes, it fails locally with java 11.

**Comment by vhalbert** [comment]
I updated JDK 11 to openjdk version "11.0.4" 2019-07-16 LTS
and I no longer fail.

**Pull request merged**
