### PR TITLE
Impala pushdown date functions + char/varchar

### PR DESCRIPTION
**Pull request by dkrapohl**

### CODE REVIEW

**Comment by shawkins** [comment]
What is the associated JIRA for this?

**Comment by dkrapohl** [comment]
No associated jira.  We required additional pushdown date functions for our queries.  I can open a storyto provide a request and usage if that's the proper protocol.

**Comment by shawkins** [comment]
Yes JIRA is the main issue tracking system, so it's our best coordination point.

**Comment by dkrapohl** [comment]
Jira is 4111.  Thanks!

**Comment by shawkins** [comment]
Merged the commit.  Thanks Don.

**Pull request closed without merging**
