### PR TITLE
TEIID-4476: Upgrade Cassandra Client library

### PR DESCRIPTION
**Pull request by kylinsoong**
Upgrade datastax cassandra driver from version 2.1.3 to 3.1.3, including some api change:
* get version api has a tiny change
* datatype name enum remove the java class type

### CODE REVIEW

**Comment by rareddy** [comment]
1) convert list and set types to array type.
2) Why you removed the searchable on index typed fields?

**Comment by kylinsoong** [comment]
> Why you removed the searchable on index typed fields?
The ColumnMetadata are not related with IndexMetadata in latest 3.x driver libraries.

**Comment by shawkins** [comment]
I'll add a change for the index metadata.

On the type conversion I'm fine with using the array mapping, but we may need to look at the binding logic  as we'd probably need to convert to the expected object class.

**Comment by shawkins** [comment]
Logged https://issues.jboss.org/browse/TEIID-4749 as a follow-on to this issue.

**Comment by kylinsoong** [comment]
I will look into this issue.

**Pull request merged**
