### PR TITLE
TEIID-3690: add a ExceptionMapper for generated rest war

### PR DESCRIPTION
**Pull request by kylinsoong**
The ExceptionMapper will return error as a xml:
~~~
<error>
  <code>ERROR</code>
  <message>message</message>
  <details>stacktrace</details>
</error>
~~~

### CODE REVIEW

**Comment by rareddy** [comment]
See if you can capture the right "http status" code, rather than "ERROR" string as code.

**Comment by kylinsoong** [comment]
@rareddy current eap 6.4 can not capture "http status", but in new version wildfly, it can capture "http status",I have comment out these code:
~~~
// if(e instanceof NotFoundException){
// code = "404";
// } else if(e instanceof InternalServerErrorException){
// code = "500";
// }
~~~
Current code can return

**Comment by kylinsoong** [comment]
As document [2] eap 6.4 use resteasy 2.3.10.Final, base on document [1], it should work, let me re-test it tomorrow.

[1] https://docs.jboss.org/resteasy/docs/2.2.1.GA/userguide/html/ExceptionHandling.html
[2] https://access.redhat.com/articles/112673

**Comment by rareddy** [comment]
The links you showed tells that if you want to use their defined Exception messages you need certain version. I am not sure what kind of exceptions we used the REST wars, but what was wrong with the above commented code?

**Comment by kylinsoong** [comment]
404 can not be captured via ExceptionMapper(I think should be a issue, [1]), this is the reason made be confused yesterday.

From Teiid side, I think commented code is correct, so add another commit, comment out it.

[1] https://issues.jboss.org/browse/RESTEASY-1229

**Comment by rareddy** [comment]
What about JSON payload? If ACCEPTS header is "application/json" then json payload needs to be sent

**Comment by kylinsoong** [comment]
@rareddy, can you review the current pull, do you have any other advice?

**Pull request merged**
