### PR TITLE
TEIID-4142: update loadmatview as a universal procedure to update Mat View

### PR DESCRIPTION
**Pull request by kylinsoong**
update loadmatview as a universal procedure that can update both Internal and External Mat View

### CODE REVIEW

**Comment by vhalbert** [comment]
Looking at:
      /* statusTable is null hints View is Internal Mat View*/
+        IF (statusTable IS NULL)

An external materialized table isn't required to define a status table, will that cause an issue here? (unless this has changed in 9.x)

**Comment by shawkins** [comment]
> An external materialized table isn't required to define a status table, will that cause an issue here? 

An external materialized view is required to have a status table.

**Comment by vhalbert** [comment]
Did this start in 9.x or is this also required in 8.12.x?   I asked, because reading the doc's, there's nothing indicating "required" as there are for other settings.

**Comment by shawkins** [comment]
No, this is not new - https://docs.jboss.org/author/display/teiid812final/External+Materialization optional=false

**Comment by kylinsoong** [comment]
@vhalbert, if you look the external document [1], In extension properties section, `teiid_rel:MATVIEW_STATUS_TABLE` optional is false. Also as [2] around line 77, if statusTable is null throw TranslatorException

[1] https://teiid.gitbooks.io/documents/content/caching/External_Materialization.html
[2] https://github.com/teiid/teiid/blob/master/engine/src/main/java/org/teiid/query/metadata/MaterializationMetadataRepository.java

**Pull request merged**
