### PR TITLE
TEIID-3725 and TEIID-3559 refactoring and adding support for materialization

### PR DESCRIPTION
**Pull request by vhalbert**
TEIID-3725 and TEIID-3559 this includes refactoring of the remote-cache logic to ue translator-object as its base, and changing remote-cache to support materialization

### CODE REVIEW

**Comment by vhalbert** [comment]
please also commit this also to the 63_8.12.x branch.

**Comment by shawkins** [comment]
This pulled cleanly into 6.3 8.12.x, but it will take me a bit to get into master.  There the object translator module.xml does say that it should have the user module added, is this correct?

**Comment by vhalbert** [comment]
the user module is set to optional=true, but the user still has add that in order for the correct dependency to be there.

**Comment by shawkins** [comment]
is it possible to use an override property instead?  it generally isn't good to have users modify module.xml files that in the dv base

**Comment by vhalbert** [comment]
Us and JDG have directions for updating module.xml to add the pojo to the class path.

**Comment by vhalbert** [comment]
And its been this way since 6.0 (teiid 8.4.x).

**Comment by shawkins** [comment]
That doesn't mean it should be left that way as that's file that could be affected by patching and forces all usage to share the same file (there is no vdb isolation, and conflicting classes would require a new translator module).

**Pull request closed without merging**
