### PR TITLE
TEIID-3617: Provide an option to Limit per user based connections

### PR DESCRIPTION
**Pull request by kylinsoong**

### CODE REVIEW

**Comment by rareddy** [comment]
There are few questions?
1) I do not see any xml persistence code?
2) Why there are operations to add/remove? This needs to be dynamic? even there can it not be "set-max-sessions = -1 is unlimited concept as we do every where else?
3) This needs to be a just attribute of the configuration, thus no operations needed in Teiid operation handler.
4) why there are "public" methods increase/decrease session count? should't these be private/package protected or protected?

**Comment by kylinsoong** [comment]
Thanks @rareddy .
Yes, the setting should be persistence, but if use a attribute, the attribute value should be complex, it may looks
~~~
user1,25;user2,35
~~~ 
do you think it's fine?

**Comment by kylinsoong** [comment]
Currently, I have changed to used a attribute, the following CLI works
~~~
[standalone@localhost:9990 /] /subsystem=teiid/transport=jdbc:write-attribute(name=max-connections-per-user,value=[("user1"=>"25"),("user2"=>"35")])
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,
        "process-state" => "reload-required"
    }
}
[standalone@localhost:9990 /] :reload
{
    "outcome" => "success",
    "result" => undefined
}
[standalone@localhost:9990 /] /subsystem=teiid/transport=jdbc:read-attribute(name=max-connections-per-user)
{
    "outcome" => "success",
    "result" => [
        ("user1" => 25L),
        ("user2" => 35L)
    ]
}
~~~
But Unit Test can not work

**Comment by kylinsoong** [comment]
Thanks @rareddy , Currently, I have changed to used the attribute, the following CLI works
~~~
[standalone@localhost:9990 /] /subsystem=teiid/transport=jdbc:write-attribute(name=max-connections-per-user,value=[("user1"=>"25"),("user2"=>"35")])
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,
        "process-state" => "reload-required"
    }
}
[standalone@localhost:9990 /] :reload
{
    "outcome" => "success",
    "result" => undefined
}
[standalone@localhost:9990 /] /subsystem=teiid/transport=jdbc:read-attribute(name=max-connections-per-user)
{
    "outcome" => "success",
    "result" => [
        ("user1" => 25L),
        ("user2" => 35L)
    ]
}
~~~
But Unit Test can not work, with stacktrace
~~~
java.lang.AssertionError: Failed due to validation errors in the model. Please fix :-) VALIDATION ERRORS IN MODEL:No value-type for type=LIST {"type" => LIST,"description" => "Max number of connections per user dedicated to limit the per user based connections, setting the value with a format '[(\"<user>\"=>\"<max-connections>\"),(\"<user>\"=>\"<max-connections>\")]'         ","expressions-allowed" => false,"nillable" => true,"access-type" => "read-write","storage" => "configuration","restart-required" => "no-services"} for attribute 'max-connections-per-user'[
    ("subsystem" => "teiid"),
    ("transport" => "*")
]
No value-type for type=LIST {"type" => LIST,"description" => "Max number of connections per user dedicated to limit the per user based connections, setting the value with a format '[(\"<user>\"=>\"<max-connections>\"),(\"<user>\"=>\"<max-connections>\")]'         ","expressions-allowed" => false,"required" => false,"nillable" => true} for operation parameter 'add.max-connections-per-user' @[
    ("subsystem" => "teiid"),
    ("transport" => "*")
]

	at org.junit.Assert.fail(Assert.java:88)
	at org.jboss.as.subsystem.test.SubsystemTestDelegate.validateDescriptionProviders(SubsystemTestDelegate.java:600)
	at org.jboss.as.subsystem.test.SubsystemTestDelegate.access$500(SubsystemTestDelegate.java:120)
	at org.jboss.as.subsystem.test.SubsystemTestDelegate$KernelServicesBuilderImpl.build(SubsystemTestDelegate.java:672)
	at org.jboss.as.subsystem.test.AbstractSubsystemBaseTest.standardSubsystemTest(AbstractSubsystemBaseTest.java:202)
	at org.jboss.as.subsystem.test.AbstractSubsystemBaseTest.standardSubsystemTest(AbstractSubsystemBaseTest.java:172)
	at org.jboss.as.subsystem.test.AbstractSubsystemBaseTest.standardSubsystemTest(AbstractSubsystemBaseTest.java:164)
	at org.teiid.jboss.TestTeiidConfiguration.testOutputPerisitence(TestTeiidConfiguration.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
~~~

**Comment by kylinsoong** [comment]
I think we should use ListAttributeDefinition, rather than SimpleAttributeDefinition, will do this tomorrow.

**Comment by kylinsoong** [comment]
@rareddy could you review the current change, especially, the session service inject code?
Thanks

**Comment by rareddy** [comment]
1) Add admin methods on VDB.java and VDBMetadata.java regarding this feature. Make sure the you are able marshell and unmarshell

Can also weed out any changed files with only spaces and provide as single commit?

**Comment by kylinsoong** [comment]
Closed due to the change move to https://github.com/teiid/teiid/pull/741

**Pull request closed without merging**
