### PR TITLE
TEIID-4572

### PR DESCRIPTION
**Pull request by shawkins**
Merged and updated changes addressing concerns with the visitor.  The execution changes still need vetted.

### CODE REVIEW

**Comment by amr-alaa-ismail** [comment]
Dear shawkins,
How to add my code here, cause I pushed some changes to my repository but found nothing here. should i create a new pull request or what to do?

**Comment by shawkins** [comment]
Yes, you can submit a new pull request that builds upon these changes.

**Comment by amr-alaa-ismail** [comment]
[This](https://github.com/teiid/teiid/pull/964) is my new pull request

**Comment by amr-alaa-ismail** [comment]
https://github.com/teiid/teiid/pull/964

**Comment by amr-alaa-ismail** [comment]
Can't connect to any repository: https://github.com/shawkins/teiid.git (https://github.com/shawkins/teiid.git: git-receive-pack not permitted)

**Comment by shawkins** [comment]
Use the command line instructions from above:

git checkout -b shawkins-TEIID-4572 master
git pull https://github.com/shawkins/teiid.git TEIID-4572

A conflict has been introduced by the header change on master, but that should be easily resolved.

**Comment by amr-alaa-ismail** [comment]
these conflicts are not even mine and i don't know how to solve them

for example, N1QLUpdateVisitor

**Comment by shawkins** [comment]
> these conflicts are not even mine and i don't know how to solve them

I have rebased and squashed this to a single commit.  You can start working from master again with this.

**Comment by amr-alaa-ismail** [comment]
Don't have permission as told you before

Can't connect to any repository: https://github.com/shawkins/teiid.git (https://github.com/shawkins/teiid.git: git-receive-pack not permitted)

**Comment by shawkins** [comment]
You don't need to push to my fork, you can submit a pull request here or there with additional changes.

**Comment by amr-alaa-ismail** [comment]
Please check this pull request
https://github.com/amr-alaa-ismail/teiid/pull/3

**Comment by shawkins** [comment]
That doesn't look based correctly either as it shows 490 changes.  

The most relevant commit I see https://github.com/amr-alaa-ismail/teiid/pull/3/commits/c96047150e10323e5a60f9bf20d47aa7e918853a seems out of date with the changes in this pull request as well.

Maybe it would be good to focus on what you are using for a test instance - instructions on how to set it up, or provide a docker image.  I can then more easily validate the execution changes.

**Comment by amr-alaa-ismail** [comment]
Please refer to this commit amr-alaa-ismail/teiid@c629d19
<https://github.com/amr-alaa-ismail/teiid/pull/3/commits/c629d19e0cf46cd18868e2c94dd02edc417d721d>

**Comment by amr-alaa-ismail** [comment]
Any updates ?!

**Comment by shawkins** [comment]
https://github.com/teiid/teiid/pull/964 is not usable.

https://github.com/amr-alaa-ismail/teiid/commit/c629d19 - looks like you are trying to make your changes consistent with this pull request, but just looking at a single commit it doesn't appear that it's further than this pull request.

Maybe it would be good to focus on what you are using for a test instance - instructions on how to set it up, or provide a docker image. I can then more easily validate the execution changes.  The SolrQueryExecution changes have no unit tests, and we need to ensure that no regressions have been introduced.

**Pull request closed without merging**
